# Generated by Django 5.2.6 on 2025-09-29 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('troubleshoots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpertise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troubleshoots.category'),
        ),
        migrations.AddField(
            model_name='userexpertise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexpertise',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_expertise', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userexpertise',
            unique_together={('user', 'category')},
        ),
    ]
