# Generated by Django 5.2.6 on 2025-09-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexpertise',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userexpertise',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='userexpertise',
            name='verified_by',
        ),
    ]
