# Generated by Django 5.2.6 on 2025-10-04 12:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userexpertise_created_at_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userexpertise',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userexpertise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userexpertise',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")]),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('SENIOR_TECH', 'Senior Technician'), ('TECH', 'Technician'), ('JUNIOR_TECH', 'Junior Technician'), ('VIEWER', 'Viewer')], db_index=True, default='VIEWER', help_text="User's permission level in the system", max_length=15),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, help_text="Brief description of the department's responsibilities"),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('DEPARTMENT', 'General Department'), ('DATABASE_AND_SOFTWARE_DEV', 'Database and Software Development'), ('CYBER_SECURITY', 'Cyber Security'), ('NETWORK', 'Network'), ('TRAINING_AND_MAINTENANCE', 'Training and maintenance')], db_index=True, default='DEPARTMENT', help_text='Select the department type', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the user account has been verified by an administrat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('IT', 'IT Specialist'), ('SYSTEM_ADMIN', 'System Administrator'), ('SOFTWARE_MAINTENANCE', 'Software Maintenance'), ('DATABASE_ADMIN', 'Database Admin'), ('CYBER_SECURITY', 'Cyber Security'), ('NETWORK_ADMIN', 'Network Administrator'), ('WEBSITE_ADMIN', 'Website Administrator'), ('TECHNOLOGY_TRAINING_OFFICER', 'Technology Training Officer'), ('HARDWARE_MAINTENANCE', 'Hardware Maintenance'), ('DATACENTER', 'Datacenter')], db_index=True, default='IT', help_text="User's functional role in the organization", max_length=50),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='accounts_de_name_4ee611_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['team_leader'], name='accounts_de_team_le_42bbc7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='accounts_us_employe_0cbd94_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department'], name='accounts_us_departm_444702_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='accounts_us_user_ty_b6cfc8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='accounts_us_is_veri_fa45d6_idx'),
        ),
        migrations.DeleteModel(
            name='UserExpertise',
        ),
    ]
