# Generated by Django 5.2.6 on 2025-10-04 12:52

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleshoots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='troubleshootingentry',
            name='troubleshoo_views_c_03e915_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='total_entries',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='path',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='troubleshootingentry',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='troubleshootingentry',
            name='downvotes_count',
        ),
        migrations.RemoveField(
            model_name='troubleshootingentry',
            name='views_count',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='troubleshooting_attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'txt', 'doc', 'docx', 'xls', 'xlsx', 'mp4', 'avi', 'mov', 'mp3', 'wav', 'zip', 'rar'])]),
        ),
        migrations.AddIndex(
            model_name='troubleshootingentry',
            index=models.Index(fields=['status', '-created_at'], name='troubleshoo_status_fe50b3_idx'),
        ),
    ]
